spring:
  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 111
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.2.15:7001
        - 192.168.2.15:7002
        - 192.168.2.15:7003
        - 192.168.2.15:7004
        - 192.168.2.15:7005
        - 192.168.2.15:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.2.18
    username: admin
    password: 1111
    virtual-host: /
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

#配置缓存首页商品分类的 key
PROTAL_CATRESULT_KEY: PROTAL_CATRESULT_KEY